[build]
  publish = "build"
  command = "npm run build"

# Force HTTPS and www to non-www redirect
[[redirects]]
  from = "http://*.bigbraintherapy.com/*"
  to = "https://bigbraintherapy.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.bigbraintherapy.com/*"
  to = "https://bigbraintherapy.com/:splat"
  status = 301
  force = true

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Specify exact paths for prerendering (better than wildcard)
[[prerender]]
  paths = [
    "/",
    "/about",
    "/emdr",
    "/resources",
    "/blog",
    "/contact-us",
    "/schedule"
  ]

# Cache control for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache control for HTML and JSON
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"